### ISSUE TITLE
Custom colors do not work

### ISSUE THREAD

**Issue by Jim3535** [VanderCat/LootBeamsFabricUpdated#1]
The custom colors configuration does not look like it works. The beams always end up being white no matter what hex color is specified.

I have tested this with multiple item types and combinations of other mod settings. Turning off render rarity color does not change this. Further, trying to override the color of a rare item does not work either.

These are screenshots from a new minecraft instance just to test this isn't related to other mods.

![2023-08-29_17 06 14](https://github.com/VanderCat/LootBeamsFabricUpdated/assets/120746893/c08810c6-6320-475d-8b06-1b1889ad9189)
![2023-08-29_17 05 26](https://github.com/VanderCat/LootBeamsFabricUpdated/assets/120746893/ecf812a7-22aa-4e2f-8df5-7bb68eacb338)
![2023-08-29_17 06 44](https://github.com/VanderCat/LootBeamsFabricUpdated/assets/120746893/7dc54e81-a3ed-440d-aee3-42e5bad23837)

Environment:
* Java is version 17.0.8
* Prism Launcher version: 7.2
* Minecraft version 1.20.1
* Fabric Loader 0.14.22

Mods:
* cloth-config-11.1.106-fabric
* fabric-api-0.87.0+1.20.1
* lootbeams-1.0.2
* modmenu-7.2.1
* Prism-1.20.1-fabric-1.0.5

**Comment by VanderCat** [comment]
Hello and thank you for bug report. It seems that it is not a bug, but an error in config description: you need to set colors like #00FF00 and not 0x00FF00 (also you can use vanilla colors like blue/red/gold etc). The correct description will be available in next release.
