### ISSUE TITLE
update for 1.20.4+?

### ISSUE THREAD

**Issue by Saiko125** [VanderCat/LootBeamsFabricUpdated#7]
maybe some update for to 1.20.4 please?

**Comment by VanderCat** [comment]
Currently there is not much major mods on minecraft newer than 1.20.1. Since i primarily ported this mod for myself i'm not interested right now in versions newer than that, but if anyone want to make a PR feel free to do it!

**Comment by Merith-TK** [comment]
Well I got good news for you
![image](https://github.com/VanderCat/LootBeamsFabricUpdated/assets/10422110/a763e180-08e6-4f93-a705-c37181ab113a)
There is no code to be edited, just the version number
![image](https://github.com/VanderCat/LootBeamsFabricUpdated/assets/10422110/3f0172ac-cb41-428a-943d-56f88a123886)


This is with my Vanillia Modpack, 
all i did was alter fabric.mod.json to support mc 1.20.4
and it works
![image](https://github.com/VanderCat/LootBeamsFabricUpdated/assets/10422110/0780b55a-1a75-4500-8ef9-a84da9e2045f)

Shaders dont even kill it
![image](https://github.com/VanderCat/LootBeamsFabricUpdated/assets/10422110/c8349f80-9613-4bf2-a7fb-48ebe39e4b92)

**Comment by Merith-TK** [comment]
update after poking itwith a stick

yeah I can litterally use the currently released jar. on 1.20.4, so all you gotta do is just mark that it works on the latest MC version on modrinth

**Comment by Saiko125** [comment]
May the god bless you with riches of the world

**Comment by VanderCat** [comment]
ahaha i didn't thought about advice about changing the version in fabric.mod.json, this trick worked for #3, and i even put ">1.19.3" in it, and i assumed that @Saiko125 actually tested the built from source version

i still have to release this new version on modrinth though.... the only reason i still didn't is it's very minor and anyone smart enough can just make a `config/fabric_loader_dependencies.json` file with this in it
```json
{
    "version": 1,
    "overrides": {
        "lootbeams": {
            "+depends": {"minecraft": ">1.19.3"}
        }
    }
}
```
see: https://fabricmc.net/wiki/tutorial:dependency_overrides
