### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by macf2802** [VanderCat/LootBeamsFabricUpdated#8]
New versions of the mod came out adding features like inventory-style tooltips, glow effect on the base and new particles and effects, is there a chance for your fabric port to get an update? Thank you in advance.

**Comment by VanderCat** [comment]
The new maintainer, amo, is a fabric hater. Here's what written on the mod page:
> No Fabric. Please don't port it either, I (Amo) don't want asked about fabric issues on a forge page.

i could however reimplement instead of port that features, but i don't like them very much
